name = "mpizenberg/cardano_dex_poc"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'mpizenberg/cardano_dex_poc'"

[repository]
user = "mpizenberg"
project = "cardano_dex_poc"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
